
# Loads default set of integrations. Do not remove.
default_config:

alexa:
  smart_home:

http:
  ssl_certificate: /ssl/fullchain.pem 
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.1.0/24

# Text to speech
tts:
  - platform: google_translate
  
input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'
    
# Note: The following two scripts are unsecured. While it's unlikely that forwarding or archiving email is going to be malicious,
# if that does become an issue, we can add credentials here to lock down permissions.
rest_command:
  forward_mail:
    url: !secret rest_forward_mail
  delete_mail:
    url: !secret rest_delete_mail
    
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
